"""empty message

Revision ID: 12c7a0f23eeb
Revises: 
Create Date: 2023-05-18 11:44:31.161786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c7a0f23eeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userr', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('userr')
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    op.create_table('userr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('userr', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
